name: immersive_reader
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.18.0 <3.0.0"

# pubspec.yaml
flutter:
  fonts:
    - family: CustomFont
      fonts:
        - asset: fonts/CustomFont-Regular.ttf
          weight: 700

dependencies:
  flutter:
    sdk: flutter

  # Add your dependencies here
  flutter_pdfview: ^1.0.0
  file_picker: ^8.0.7
  epubx: ^4.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_lints: ^2.0.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
